services:
  - type: worker
    name: vet-bot
    env: python
    region: frankfurt  # або будь-який регіон
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: BOT_TIMEZONE
        sync: false
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SHEETS_WORKSHEET_NAME
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
